// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMgVofaRLZd3dHxttZrW4va67h6Z-2jvU',
    appId: '1:30920803024:web:9295f1f7912cf695db54d5',
    messagingSenderId: '30920803024',
    projectId: 'srswapper-d5587',
    authDomain: 'srswapper-d5587.firebaseapp.com',
    storageBucket: 'srswapper-d5587.firebasestorage.app',
    measurementId: 'G-X0981QSFSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01T12scTLGDk8_5nv32hK9xLL5IkNzk0',
    appId: '1:30920803024:android:6a16c994f4db4c84db54d5',
    messagingSenderId: '30920803024',
    projectId: 'srswapper-d5587',
    storageBucket: 'srswapper-d5587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2cyjDWIvl8iom5z0QNoX64N6tskqhOo',
    appId: '1:30920803024:ios:d36bf1f31f2dc706db54d5',
    messagingSenderId: '30920803024',
    projectId: 'srswapper-d5587',
    storageBucket: 'srswapper-d5587.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2cyjDWIvl8iom5z0QNoX64N6tskqhOo',
    appId: '1:30920803024:ios:d36bf1f31f2dc706db54d5',
    messagingSenderId: '30920803024',
    projectId: 'srswapper-d5587',
    storageBucket: 'srswapper-d5587.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );
}
